// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoej40Mce-tOXS9HeJ6a-uACt2vWr-3hA',
    appId: '1:649806035247:web:e7abfd7f645c7b243209da',
    messagingSenderId: '649806035247',
    projectId: 'careerlens-ai-89c5c',
    authDomain: 'careerlens-ai-89c5c.firebaseapp.com',
    storageBucket: 'careerlens-ai-89c5c.firebasestorage.app',
    measurementId: 'G-KKMV9JL5TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIHmzV8QojCoXrwQRaWf0KwsZAvDnTV8s',
    appId: '1:649806035247:android:287d0c65442901d53209da',
    messagingSenderId: '649806035247',
    projectId: 'careerlens-ai-89c5c',
    storageBucket: 'careerlens-ai-89c5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh38-AONPccjgsuXsaA1UULbQxo4FcMhU',
    appId: '1:649806035247:ios:8e97360376d054f73209da',
    messagingSenderId: '649806035247',
    projectId: 'careerlens-ai-89c5c',
    storageBucket: 'careerlens-ai-89c5c.firebasestorage.app',
    androidClientId: '649806035247-rec7bbh0ee2qhdr9grev0okbvdinno9s.apps.googleusercontent.com',
    iosClientId: '649806035247-1rhkgal5ba8nkbdd6ebahup0k60qmkik.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh38-AONPccjgsuXsaA1UULbQxo4FcMhU',
    appId: '1:649806035247:ios:8e97360376d054f73209da',
    messagingSenderId: '649806035247',
    projectId: 'careerlens-ai-89c5c',
    storageBucket: 'careerlens-ai-89c5c.firebasestorage.app',
    androidClientId: '649806035247-rec7bbh0ee2qhdr9grev0okbvdinno9s.apps.googleusercontent.com',
    iosClientId: '649806035247-1rhkgal5ba8nkbdd6ebahup0k60qmkik.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoej40Mce-tOXS9HeJ6a-uACt2vWr-3hA',
    appId: '1:649806035247:web:918e28e4f8b0a0313209da',
    messagingSenderId: '649806035247',
    projectId: 'careerlens-ai-89c5c',
    authDomain: 'careerlens-ai-89c5c.firebaseapp.com',
    storageBucket: 'careerlens-ai-89c5c.firebasestorage.app',
    measurementId: 'G-6L57DFG6XY',
  );
}
